// angular-jokes/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit{

  constructor(private router: Router) {

  }
  
  ngOnInit(): void {
    const isConnected = localStorage.getItem("isConnected");
    
    if (isConnected === null) {
      this.router.navigate(["/login"]);
    }
  }
  
}

<h1>Accueil</h1>
<p>Ce site vous permet de lire, envoyer et liker des blagues de toutes catégories</p>

// react-jokes/src/components/Home/Home.jsx
import { useNavigate } from 'react-router-dom'

const Home = () => {

    const homeParagraphStyle = {
        margin: "20px"
    }

    return (
        <>
            <h1>Home</h1>
            <p style={homeParagraphStyle}>Ce site vous permet de lire, envoyer et liker des blagues de toutes catégories</p>
        </>
    )
}

export default Home
